# -*- coding: utf-8 -*-

DATA_CARDS = [
    # B-RANK CARDS (Chapter 1)
    {"name": "Refleczer", "rank": "B", "chapter": 1},
    {"name": "Metall C-15", "rank": "B", "chapter": 1},
    {"name": "Ball De Voux", "rank": "B", "chapter": 1},
    {"name": "Dig Labour", "rank": "B", "chapter": 1},

    # A-RANK CARDS
    {"name": "Batton", "rank": "A", "chapter": 2},
    {"name": "Sine Fall", "rank": "A", "chapter": 2},
    {"name": "Telly Auto", "rank": "A", "chapter": 3},
    {"name": "Mega Pin", "rank": "A", "chapter": 3},
    {"name": "Aura", "rank": "A", "chapter": 4},

    # S-RANK CARDS (General / Bosses)
    {"name": "Maverick Hunter X", "rank": "S", "chapter": 1},
    {"name": "Zero's Resolve", "rank": "S", "chapter": 1},
    {"name": "Vile's Ambition", "rank": "S", "chapter": 2},
    {"name": "Sigma's Command", "rank": "S", "chapter": 2},
    {"name": "Command Mission", "rank": "S", "chapter": 3},
    {"name": "Cyber Peacock", "rank": "S", "chapter": 3},
    {"name": "Storm Eagle", "rank": "S", "chapter": 4},
    {"name": "Flame Stagger", "rank": "S", "chapter": 4},
    {"name": "Magma Dragoon", "rank": "S", "chapter": 5},
    {"name": "Split Mushroom", "rank": "S", "chapter": 5},
    {"name": "Slash Beast", "rank": "S", "chapter": 6},
    {"name": "Frost Walrus", "rank": "S", "chapter": 6},
    {"name": "Jet Stingray", "rank": "S", "chapter": 7},
    {"name": "Spiral Pegasus", "rank": "S", "chapter": 7},
    {"name": "Tidal Whale", "rank": "S", "chapter": 8},
    {"name": "Grizzly Slash", "rank": "S", "chapter": 8},
    {"name": "Dark Dizzy", "rank": "S", "chapter": 9},
    {"name": "Shadow Fire", "rank": "S", "chapter": 9},
    {"name": "DiVE World", "rank": "S", "chapter": 10},

    # S-RANK CARDS (#101 to #176 Character-Exclusive)
    {"name": "Charge Shot (X)", "rank": "S", "chapter": 1},
    {"name": "Z-Saber (Zero)", "rank": "S", "chapter": 1},
    {"name": "Axl Bullets", "rank": "S", "chapter": 1},
    {"name": "Giga Crush", "rank": "S", "chapter": 2},
    {"name": "Double Cyclone", "rank": "S", "chapter": 2},
    {"name": "Nova Strike", "rank": "S", "chapter": 2},
    {"name": "Soul Body", "rank": "S", "chapter": 3},
    {"name": "Rising Fire", "rank": "S", "chapter": 3},
    {"name": "Lightning Web", "rank": "S", "chapter": 3},
    {"name": "Frost Tower", "rank": "S", "chapter": 4},
    {"name": "Aiming Laser", "rank": "S", "chapter": 4},
    {"name": "Ground Hunter", "rank": "S", "chapter": 4},
    {"name": "Spike Ball", "rank": "S", "chapter": 5},
    {"name": "Flash Bomber", "rank": "S", "chapter": 5},
    {"name": "Crescent Laser", "rank": "S", "chapter": 5},
    {"name": "Wing Spiral", "rank": "S", "chapter": 6},
    {"name": "Gaea Shield", "rank": "S", "chapter": 6},
    {"name": "Yammar Option", "rank": "S", "chapter": 6},
    {"name": "Ground Dash", "rank": "S", "chapter": 7},
    {"name": "Magma Blade", "rank": "S", "chapter": 7},
    {"name": "Ice Burst", "rank": "S", "chapter": 7},
    {"name": "Meteor Rain", "rank": "S", "chapter": 8},
    {"name": "Metal Anchor", "rank": "S", "chapter": 8},
    {"name": "Ray Arrow", "rank": "S", "chapter": 8},
    {"name": "Volt Tornado", "rank": "S", "chapter": 9},
    {"name": "Splash Laser", "rank": "S", "chapter": 9},
    {"name": "Circle Blaze", "rank": "S", "chapter": 9},
    {"name": "Moving Wheel", "rank": "S", "chapter": 10},
    {"name": "Sniper Missile", "rank": "S", "chapter": 10},
    {"name": "Wind Cutter", "rank": "S", "chapter": 10},
    {"name": "Explosion", "rank": "S", "chapter": 11},
    {"name": "Double Barrier", "rank": "S", "chapter": 11},
    {"name": "Plasma Gun", "rank": "S", "chapter": 11},
    {"name": "Drift Diamond", "rank": "S", "chapter": 12},
    {"name": "Crystal Wall", "rank": "S", "chapter": 12},
    {"name": "Green Spinner", "rank": "S", "chapter": 12},
    {"name": "Shining Ray", "rank": "S", "chapter": 13},
    {"name": "Shadow Runner", "rank": "S", "chapter": 13},
    {"name": "Squeeze Bomb", "rank": "S", "chapter": 13},
    {"name": "Electric Shock", "rank": "S", "chapter": 14},
    {"name": "Buster Barrage", "rank": "S", "chapter": 14},
    {"name": "Flame Burner", "rank": "S", "chapter": 14},
    {"name": "Giga Buster", "rank": "S", "chapter": 15},
    {"name": "Hyper Buster", "rank": "S", "chapter": 15},
    {"name": "Spiral Crush", "rank": "S", "chapter": 15},
    {"name": "Atomic Fire", "rank": "S", "chapter": 16},
    {"name": "Leaf Shield", "rank": "S", "chapter": 16},
    {"name": "Time Stopper", "rank": "S", "chapter": 16},
    {"name": "Metal Blade", "rank": "S", "chapter": 17},
    {"name": "Bubble Lead", "rank": "S", "chapter": 17},
    {"name": "Air Shooter", "rank": "S", "chapter": 17},
    {"name": "Crash Bomber", "rank": "S", "chapter": 18},
    {"name": "Flash Stopper", "rank": "S", "chapter": 18},
    {"name": "Quick Boomerang", "rank": "S", "chapter": 18},
    {"name": "Gemini Laser", "rank": "S", "chapter": 5},
    {"name": "Needle Cannon", "rank": "S", "chapter": 5},
    {"name": "Hard Knuckle", "rank": "S", "chapter": 6},
    {"name": "Search Snake", "rank": "S", "chapter": 6},
    {"name": "Magnet Missile", "rank": "S", "chapter": 7},
    {"name": "Shadow Blade", "rank": "S", "chapter": 7},
    {"name": "Spark Shock", "rank": "S", "chapter": 8},
    {"name": "Top Spin", "rank": "S", "chapter": 8},
    {"name": "Dive Missile", "rank": "S", "chapter": 9},
    {"name": "Skull Barrier", "rank": "S", "chapter": 9},
    {"name": "Ring Boomerang", "rank": "S", "chapter": 10},
    {"name": "Rain Flush", "rank": "S", "chapter": 10},
    {"name": "Pharaoh Shot", "rank": "S", "chapter": 11},
    {"name": "Flash Stopper EX", "rank": "S", "chapter": 11},
    {"name": "Dust Crusher", "rank": "S", "chapter": 12},
    {"name": "Drill Bomb", "rank": "S", "chapter": 12},
    {"name": "DiVE Armor RiCO", "rank": "S", "chapter": 15},
]

# Maps card name to its full dictionary object (including rank and chapter)
CARD_LOOKUP = {c["name"]: c for c in DATA_CARDS}

STAR_UPGRADE_COSTS = {
    1: {"bolts": 5000, "patches": 10},
    2: {"bolts": 12000, "patches": 25},
    3: {"bolts": 25000, "patches": 50},
    4: {"bolts": 50000, "patches": 100},
    5: {"bolts": 100000, "patches": 200},
}