# -*- coding: utf-8 -*-
from Config import RANK_PRIORITY

DATA_CHARACTERS = [
    # --- B-RANK CHARACTERS (5) ---
    {"name": "X", "rank": "B", "chapter": 1},
    {"name": "Axl", "rank": "B", "chapter": 1},
    {"name": "Massimo", "rank": "B", "chapter": 1},
    {"name": "Pallette", "rank": "B", "chapter": 1},
    {"name": "Servbot", "rank": "B", "chapter": 4},

    # --- A-RANK CHARACTERS (19) ---
    {"name": "Zero", "rank": "A", "chapter": 1},
    {"name": "Alia", "rank": "A", "chapter": 1},
    {"name": "Marino", "rank": "A", "chapter": 1},
    {"name": "Cinnamon", "rank": "A", "chapter": 1},
    {"name": "Vile", "rank": "A", "chapter": 1},
    {"name": "Ferham", "rank": "A", "chapter": 2},          # Adjusted to A-Rank
    {"name": "Layer", "rank": "A", "chapter": 2},
    {"name": "Bit", "rank": "A", "chapter": 2},
    {"name": "Mega Man", "rank": "A", "chapter": 3},
    {"name": "Roll", "rank": "A", "chapter": 3},
    {"name": "Super Mega Man", "rank": "A", "chapter": 3},  # Adjusted to A-Rank
    {"name": "Volnutt", "rank": "A", "chapter": 4},
    {"name": "MegaMan.EXE", "rank": "A", "chapter": 4},     # Adjusted to A-Rank
    {"name": "Vent", "rank": "A", "chapter": 7},
    {"name": "Aile", "rank": "A", "chapter": 7},
    {"name": "Signas", "rank": "A", "chapter": 7},
    {"name": "Grey", "rank": "A", "chapter": 11},
    {"name": "Ashe", "rank": "A", "chapter": 11},
    {"name": "Roll.EXE", "rank": "A", "chapter": 12},

    # --- S-RANK CHARACTERS (105) ---
    {"name": "First Armor X", "rank": "S", "chapter": 1},
    {"name": "Black Zero", "rank": "S", "chapter": 1},
    {"name": "Second Armor X", "rank": "S", "chapter": 2},
    {"name": "Ultimate Armor X", "rank": "S", "chapter": 2},
    {"name": "Proto Man", "rank": "S", "chapter": 2},       # Confirmed S-Rank
    {"name": "Command Mission X", "rank": "S", "chapter": 3},
    {"name": "Awakened Zero", "rank": "S", "chapter": 3},
    {"name": "Bass", "rank": "S", "chapter": 3},            # Adjusted to S-Rank
    {"name": "Tron Bonne", "rank": "S", "chapter": 4},
    {"name": "Chaud & ProtoMan.EXE", "rank": "S", "chapter": 4},
    {"name": "ProtoMan.EXE", "rank": "S", "chapter": 4},    # Adjusted to S-Rank
    {"name": "Star Force Mega Man", "rank": "S", "chapter": 5},
    {"name": "Harp Note", "rank": "S", "chapter": 5},
    {"name": "Zero (Mega Man Zero)", "rank": "S", "chapter": 5},
    {"name": "Ciel", "rank": "S", "chapter": 5},
    {"name": "Leviathan", "rank": "S", "chapter": 5},
    {"name": "Harpuia", "rank": "S", "chapter": 6},
    {"name": "Fefnir", "rank": "S", "chapter": 6},
    {"name": "Phantom", "rank": "S", "chapter": 6},
    {"name": "Copy X", "rank": "S", "chapter": 6},
    {"name": "Omega", "rank": "S", "chapter": 6},
    {"name": "Model ZX", "rank": "S", "chapter": 7},
    {"name": "Model OX", "rank": "S", "chapter": 7},
    {"name": "Iris", "rank": "S", "chapter": 7},
    {"name": "Colonel", "rank": "S", "chapter": 8},
    {"name": "Iris -Another-", "rank": "S", "chapter": 8},
    {"name": "Ultimate Armor X (CM)", "rank": "S", "chapter": 8},
    {"name": "Absolute Zero", "rank": "S", "chapter": 8},
    {"name": "Third Armor X", "rank": "S", "chapter": 8},
    {"name": "Fourth Armor X", "rank": "S", "chapter": 9},
    {"name": "Falcon Armor X", "rank": "S", "chapter": 9},
    {"name": "Gaea Armor X", "rank": "S", "chapter": 9},
    {"name": "Shadow Armor X", "rank": "S", "chapter": 9},
    {"name": "Blade Armor X", "rank": "S", "chapter": 9},
    {"name": "Next Armor X", "rank": "S", "chapter": 10},
    {"name": "DiVE Armor X", "rank": "S", "chapter": 10},
    {"name": "DiVE Armor Zero", "rank": "S", "chapter": 10},
    {"name": "DiVE Armor Axl", "rank": "S", "chapter": 10},
    {"name": "DiVE Armor Iris", "rank": "S", "chapter": 10},
    {"name": "Model A", "rank": "S", "chapter": 11},
    {"name": "Prometheus", "rank": "S", "chapter": 11},
    {"name": "Pandora", "rank": "S", "chapter": 11},
    {"name": "Bass.EXE", "rank": "S", "chapter": 12},
    {"name": "Colonel.EXE", "rank": "S", "chapter": 12},
    {"name": "Hub Style MegaMan.EXE", "rank": "S", "chapter": 12},
    {"name": "Rogue", "rank": "S", "chapter": 13},
    {"name": "Acid Ace", "rank": "S", "chapter": 13},
    {"name": "Dark MegaMan.EXE", "rank": "S", "chapter": 13},
    {"name": "Craft", "rank": "S", "chapter": 14},
    {"name": "Elpizo", "rank": "S", "chapter": 14},
    {"name": "Lumine", "rank": "S", "chapter": 14},
    {"name": "Red", "rank": "S", "chapter": 14},
    {"name": "X-Kai", "rank": "S", "chapter": 15},
    {"name": "DiVE Armor RiCO", "rank": "S", "chapter": 15},
    {"name": "DiVE Armor ViA", "rank": "S", "chapter": 15},
    {"name": "RiCO", "rank": "S", "chapter": 16},
    {"name": "ViA", "rank": "S", "chapter": 16},
    {"name": "iCX", "rank": "S", "chapter": 16},
    {"name": "Erato Ho", "rank": "S", "chapter": 16},
    {"name": "Droitclair", "rank": "S", "chapter": 17},
    {"name": "Ange", "rank": "S", "chapter": 17},
    {"name": "Super Bass", "rank": "S", "chapter": 17},
    {"name": "Ultimate Armor X (X8)", "rank": "S", "chapter": 18},
    {"name": "Master DiVE Armor X", "rank": "S", "chapter": 18},
    {"name": "Sigma", "rank": "S", "chapter": 10},
    {"name": "Kaiser Sigma", "rank": "S", "chapter": 12},
    {"name": "Gate", "rank": "S", "chapter": 12},
    {"name": "Dynamo", "rank": "S", "chapter": 8},
    {"name": "Epsilon", "rank": "S", "chapter": 13},
    {"name": "Nightmare Zero", "rank": "S", "chapter": 11},
    {"name": "General", "rank": "S", "chapter": 9},
    {"name": "iCO", "rank": "S", "chapter": 5},
    {"name": "DiVE Armor iCO", "rank": "S", "chapter": 15},
    {"name": "Next DiVE Armor X", "rank": "S", "chapter": 16},
    {"name": "ViA -≡-", "rank": "S", "chapter": 15},
    {"name": "GutsMan.EXE", "rank": "S", "chapter": 7},
    {"name": "Bass GS", "rank": "S", "chapter": 12},
    {"name": "Cross Fusion MegaMan", "rank": "S", "chapter": 13},
    {"name": "Super Armor Megaman", "rank": "S", "chapter": 12},
    {"name": "Swimsuit Roll", "rank": "S", "chapter": 3},
    {"name": "Swimsuit Iris", "rank": "S", "chapter": 4},
    {"name": "Swimsuit Ferham", "rank": "S", "chapter": 5},
    {"name": "Swimsuit Layer", "rank": "S", "chapter": 5},
    {"name": "Swimsuit Alia", "rank": "S", "chapter": 6},
    {"name": "Swimsuit Tron", "rank": "S", "chapter": 6},
    {"name": "Swimsuit Ciel", "rank": "S", "chapter": 7},
    {"name": "Swimsuit Pallette", "rank": "S", "chapter": 7},
    {"name": "Swimsuit iCO", "rank": "S", "chapter": 8},
    {"name": "Swimsuit RiCO", "rank": "S", "chapter": 8},
    {"name": "Halloween Vile", "rank": "S", "chapter": 4},
    {"name": "Halloween Marino", "rank": "S", "chapter": 5},
    {"name": "Halloween Axl", "rank": "S", "chapter": 6},
    {"name": "Halloween Roll", "rank": "S", "chapter": 7},
    {"name": "Halloween Sigma", "rank": "S", "chapter": 8},
    {"name": "Halloween ViA", "rank": "S", "chapter": 11},
    {"name": "Christmas Bit", "rank": "S", "chapter": 4},
    {"name": "Christmas Leviathan", "rank": "S", "chapter": 6},
    {"name": "Christmas Ciel", "rank": "S", "chapter": 7},
    {"name": "Christmas Alia", "rank": "S", "chapter": 8},
    {"name": "Christmas RiCO", "rank": "S", "chapter": 9},
    {"name": "New Year Cinnamon", "rank": "S", "chapter": 5},
    {"name": "New Year Iris", "rank": "S", "chapter": 7},
    {"name": "New Year Zero", "rank": "S", "chapter": 8},
    {"name": "Valentine Ciel", "rank": "S", "chapter": 6},
    {"name": "Valentine Iris", "rank": "S", "chapter": 7},
]

# Maps character name to its full dictionary object (including rank and chapter)
CHAR_LOOKUP = {c["name"]: c for c in DATA_CHARACTERS}
STAR_COSTS = (30, 40, 50, 70, 110)
UNLOCK_COST = 40