# -*- coding: utf-8 -*-
"""
Weapons.py
Contains the complete, duplicate-free roster of 97 weapons from Mega Man X DiVE Offline.
"""

DATA_WEAPONS = [
    # --- B-RANK WEAPONS (8) ---
    {"name": "Mega Buster", "rank": "B", "chapter": 1},
    {"name": "Military Buster", "rank": "B", "chapter": 1},
    {"name": "Wind Pressure Buster", "rank": "B", "chapter": 1},
    {"name": "Standard Saber", "rank": "B", "chapter": 1},
    {"name": "Beam Rapier", "rank": "B", "chapter": 1},
    {"name": "Laser Rifle", "rank": "B", "chapter": 1},
    {"name": "Triangle Gun", "rank": "B", "chapter": 1},
    {"name": "Energy Cannon", "rank": "B", "chapter": 1},

    # --- A-RANK WEAPONS (14) ---
    {"name": "Arrow Buster", "rank": "A", "chapter": 2},
    {"name": "Shadow Blade Buster", "rank": "A", "chapter": 2},
    {"name": "Sonic Buster", "rank": "A", "chapter": 2},
    {"name": "Triangular Saber", "rank": "A", "chapter": 2},
    {"name": "Elite Lance", "rank": "A", "chapter": 2},
    {"name": "High-speed Rifle", "rank": "A", "chapter": 3},
    {"name": "Beam Machine Gun", "rank": "A", "chapter": 3},
    {"name": "Ion Rifle", "rank": "A", "chapter": 3},
    {"name": "Gatling Gun", "rank": "A", "chapter": 3},
    {"name": "Gas Emitter", "rank": "A", "chapter": 4},
    {"name": "Compressed Spray Gun", "rank": "A", "chapter": 4},
    {"name": "Burning Spray Gun", "rank": "A", "chapter": 4},
    {"name": "Snowy Spray Gun", "rank": "A", "chapter": 4},
    {"name": "Cannon", "rank": "A", "chapter": 5},

    # --- S-RANK WEAPONS (75) ---
    {"name": "Ultimate Blast", "rank": "S", "chapter": 2},
    {"name": "Doom Blade", "rank": "S", "chapter": 2},
    {"name": "Sniper Buster", "rank": "S", "chapter": 2},
    {"name": "Demon Blade Muramasa", "rank": "S", "chapter": 3},
    {"name": "Nightmare", "rank": "S", "chapter": 3},
    {"name": "Air Buster", "rank": "S", "chapter": 3},
    {"name": "Destructive Laser", "rank": "S", "chapter": 3},
    {"name": "Red Lotus Saber", "rank": "S", "chapter": 4},
    {"name": "Aqua Buster", "rank": "S", "chapter": 4},
    {"name": "Acidic Machine Gun", "rank": "S", "chapter": 4},
    {"name": "Miracle Blade", "rank": "S", "chapter": 5},
    {"name": "Jet Vortex Buster", "rank": "S", "chapter": 5},
    {"name": "Freezing Dominator", "rank": "S", "chapter": 5},
    {"name": "Assault Equipment", "rank": "S", "chapter": 5},
    {"name": "Giga Crash Buster", "rank": "S", "chapter": 6},
    {"name": "V-Saber", "rank": "S", "chapter": 6},
    {"name": "Ancient Relic", "rank": "S", "chapter": 6},
    {"name": "The Deconstructor", "rank": "S", "chapter": 6},
    {"name": "Light Bender", "rank": "S", "chapter": 6},
    {"name": "Deicide's Will", "rank": "S", "chapter": 6},
    {"name": "Biochemical Buster", "rank": "S", "chapter": 7},
    {"name": "Twin Fangs", "rank": "S", "chapter": 7},
    {"name": "The Evil Eye", "rank": "S", "chapter": 7},
    {"name": "Gator Fangs", "rank": "S", "chapter": 7},
    {"name": "Fantasia Comet", "rank": "S", "chapter": 7},
    {"name": "Sonic Blade", "rank": "S", "chapter": 8},
    {"name": "Nova Strike Buster", "rank": "S", "chapter": 8},
    {"name": "Boomerang Blade", "rank": "S", "chapter": 8},
    {"name": "Icicle Fang", "rank": "S", "chapter": 8},
    {"name": "Assault Rifle", "rank": "S", "chapter": 8},
    {"name": "Heart Spray Gun", "rank": "S", "chapter": 8},
    {"name": "Howling Storm", "rank": "S", "chapter": 8},
    {"name": "Darkness Scythe", "rank": "S", "chapter": 9},
    {"name": "Pulsar Cannon", "rank": "S", "chapter": 9},
    {"name": "Thunder Sword", "rank": "S", "chapter": 9},
    {"name": "SuperMag Gun", "rank": "S", "chapter": 9},
    {"name": "Glittering Spark", "rank": "S", "chapter": 9},
    {"name": "Bubble Bomber", "rank": "S", "chapter": 9},
    {"name": "DiVE Buster", "rank": "S", "chapter": 10},
    {"name": "DiVE Saber", "rank": "S", "chapter": 10},
    {"name": "Hawk Precision Buster", "rank": "S", "chapter": 10},
    {"name": "Shark Toothed Anchor", "rank": "S", "chapter": 10},
    {"name": "Scarlet Tyrant", "rank": "S", "chapter": 10},
    {"name": "Explosive Flamethrower", "rank": "S", "chapter": 10},
    {"name": "Star Breaker Cannon", "rank": "S", "chapter": 10},
    {"name": "Model ZX Saber", "rank": "S", "chapter": 11},
    {"name": "Berserker Great Sword", "rank": "S", "chapter": 11},
    {"name": "Purgatory Machine Gun", "rank": "S", "chapter": 11},
    {"name": "Poisonous Cloud Spray Gun", "rank": "S", "chapter": 11},
    {"name": "Absolute Freeze", "rank": "S", "chapter": 11},
    {"name": "Stellar Buster", "rank": "S", "chapter": 11},
    {"name": "Singularity Slasher", "rank": "S", "chapter": 12},
    {"name": "Heart of Gold", "rank": "S", "chapter": 12},
    {"name": "Electric Current Spray Gun", "rank": "S", "chapter": 12},
    {"name": "Light Wave Cannon", "rank": "S", "chapter": 12},
    {"name": "Absolute DiVE Buster", "rank": "S", "chapter": 12},
    {"name": "Crimson Scythe", "rank": "S", "chapter": 13},
    {"name": "Grudge Axe", "rank": "S", "chapter": 13},
    {"name": "Falcon Ballista", "rank": "S", "chapter": 13},
    {"name": "Pyro Executioner", "rank": "S", "chapter": 13},
    {"name": "Ragnarok Cannon", "rank": "S", "chapter": 13},
    {"name": "Shooting Dragon", "rank": "S", "chapter": 13},
    {"name": "Bifrost Blade", "rank": "S", "chapter": 14},
    {"name": "Lover's Gaze", "rank": "S", "chapter": 14},
    {"name": "Zero Virus Saber", "rank": "S", "chapter": 14},
    {"name": "Savage Tusk of Thunder", "rank": "S", "chapter": 14},
    {"name": "Essence of the Abyss", "rank": "S", "chapter": 14},
    {"name": "Cannon God", "rank": "S", "chapter": 14},
    {"name": "Drill Head Cannon", "rank": "S", "chapter": 14},
    {"name": "ViA Twin Blade", "rank": "S", "chapter": 15},
    {"name": "Eternity Blade", "rank": "S", "chapter": 15},
    {"name": "Atomic Disintegration", "rank": "S", "chapter": 15},
    {"name": "Neon Laser", "rank": "S", "chapter": 15},
    {"name": "Napalm's Head", "rank": "S", "chapter": 15},
    {"name": "Destroyer", "rank": "S", "chapter": 15},
]

# Exported lookup dictionary required by Execute.py for rank lookup
WEAPON_LOOKUP = {w["name"]: w["rank"] for w in DATA_WEAPONS}